apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: react-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/AnaisUrlichs/react-article-display
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deploy/manifests/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: react-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: react-app
  targetNamespace: app
